### ISSUE TITLE
I got an exception 

### ISSUE THREAD

**Issue by RocketFlash** [MiXaiLL76/faster_coco_eval#12]
Hi @MiXaiLL76 !

I got an exception on this line:

https://github.com/MiXaiLL76/faster_coco_eval/blob/611749b834f70d0e7969cd2af42e3ed1b76900d2/faster_coco_eval/core/faster_eval_api.py#L140C13-L140C13

```bash self.ground_truth_orig_id = np.array(self.eval['ground_truth_orig_id']).reshape(self.ground_truth_shape) ValueError: cannot reshape array of size 39720 into shape (20,4,10,newaxis) ```

After that the rest calculated well. Could you explain what this block of code do and what I am doing wrong?

**Comment by MiXaiLL76** [comment]
There are experimental functions that can produce such an error, I’m still figuring out how to fix them.
They don’t affect the main coco validation, it’s just an additional metric among the metrics)
