### ISSUE TITLE
Error when instanciating a Curves object

### ISSUE THREAD

**Issue by patrontheo** [MiXaiLL76/faster_coco_eval#21]
**Describe the bug**
I can't instanciate a Curves object.

**To Reproduce**
```python
from faster_coco_eval import COCO
from faster_coco_eval.extra import Curves

cocoGt = COCO('gt.json')
cocoDt = cocoGt.loadRes('pred.json')

cur = Curves(cocoGt, cocoDt, iou_tresh=0.5, iouType='bbox')
```

> KeyError                                  Traceback (most recent call last)
> Cell In[2], line 1
> ----> 1 cur = Curves(coco_gt, coco_gt, iou_tresh=0.5, iouType='bbox')
> 
> File ~/mambaforge/envs/fiftyone/lib/python3.10/site-packages/faster_coco_eval/extra/extra.py:33, in ExtraEval.__init__(self, cocoGt, cocoDt, iouType, min_score, iou_tresh, recall_count, useCats)
>      30 assert self.cocoGt is not None, "cocoGt is empty"
>      32 if (self.cocoGt is not None) and (self.cocoDt is not None):
> ---> 33     self.evaluate()
> 
> File ~/mambaforge/envs/fiftyone/lib/python3.10/site-packages/faster_coco_eval/extra/extra.py:52, in ExtraEval.evaluate(self)
>      48 cocoEval.params.useCats = int(self.useCats)  # Выключение labels
>      50 self.cocoEval = cocoEval
> ---> 52 cocoEval.evaluate()
>      53 cocoEval.accumulate()
>      55 self.eval = cocoEval.eval
> 
> File ~/mambaforge/envs/fiftyone/lib/python3.10/site-packages/faster_coco_eval/core/faster_eval_api.py:54, in COCOeval_faster.evaluate(self)
>      52 elif p.iouType == "keypoints":
>      53     computeIoU = self.computeOks
> ---> 54 self.ious = {
>      55     (imgId, catId): computeIoU(imgId, catId)
>      56     for imgId in p.imgIds
>      57     for catId in catIds
>      58 }  # bottleneck
> ...
> --> 206 inds = np.argsort([-d["score"] for d in dt], kind="mergesort")
>     207 dt = [dt[i] for i in inds]
>     208 if len(dt) > p.maxDets[-1]:
> 
> KeyError: 'score'

**Expected behavior**
I expect this command to run without errors.

**Additional context**
The ground truths and annotation files are the same as in my previous issue (#19).

**Comment by MiXaiLL76** [comment]
I can not reproduce:

```py
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from faster_coco_eval import COCO
>>> from faster_coco_eval.extra import Curves
>>> import faster_coco_eval
>>> faster_coco_eval.__version__
'1.4.3'
>>> cocoGt = COCO('gt.json')
>>> cocoDt = cocoGt.loadRes('preds.json')
>>> cur = Curves(cocoGt, cocoDt, iou_tresh=0.5, iouType='bbox')
>>> cur
<faster_coco_eval.extra.curves.Curves object at 0x7f8684e7bb20>
>>>
```

**Comment by MiXaiLL76** [comment]
@patrontheo Are there any new examples of the bug? or I close this issue

**Comment by patrontheo** [comment]
@MiXaiLL76  I tried again and it works, not sure what triggered the error before, sorry about that. Thanks for your answer :)
