### ISSUE TITLE
Install of v1.6.0 fails on windows + mac

### ISSUE THREAD

**Issue by SkafteNicki** [MiXaiLL76/faster_coco_eval#39]
**Describe the bug**
Hi, Nicki from Torchmetrics team here. Thanks for the great work in this repository, we could not have implemented it our self which is why we gladly try to support it as backend.

Out CI is trying to update to v1.6.0 and we are seeing the installation of the package failing on both windows and mac, but working on ubuntu. See this:
PR: https://github.com/Lightning-AI/torchmetrics/pull/2750
Failing mac build: https://github.com/Lightning-AI/torchmetrics/actions/runs/11252976351/job/31287372620?pr=2750
Failing windows build: https://github.com/Lightning-AI/torchmetrics/actions/runs/11252976351/job/31287373485?pr=2750

Any help on how to fix this will be appreciated.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Borda** [comment]
@MiXaiLL76 will you have time to check this out? 🦩

**Comment by MiXaiLL76** [comment]
> @MiXaiLL76 will you have time to check this out? 🦩

Hi! Thanks for the issue! I'll look into it as soon as possible and get back with a fix!

**Comment by MiXaiLL76** [comment]
https://github.com/MiXaiLL76/faster_coco_eval/pull/41

Regarding another bug, I wrote here

https://github.com/Lightning-AI/torchmetrics/pull/2750#issuecomment-2403450693

**Comment by MiXaiLL76** [comment]
faster-coco-eval 1.6.2 Available on pypi.

**Comment by MiXaiLL76** [comment]
How are the build tests? Does everything work on macos and windows?

**Comment by SkafteNicki** [comment]
@MiXaiLL76 all windows builds are now installing and passing, but all macos builds are still failing at the installation:
https://github.com/Lightning-AI/torchmetrics/actions/runs/11271068805/job/31343173001?pr=2750

**Comment by MiXaiLL76** [comment]
> @MiXaiLL76 all windows builds are now installing and passing, but all macos builds are still failing at the installation: https://github.com/Lightning-AI/torchmetrics/actions/runs/11271068805/job/31343173001?pr=2750

Can you tell me what version of pybind11 is being used?

**Comment by MiXaiLL76** [comment]
With macos it's some kind of compiler problem, very strange. I found a laptop with macos and took it for the evening, I can do tests.

**Comment by MiXaiLL76** [comment]
I am happy to announce that I have solved the problem with macOS!
It was an interesting investigation) And a very small fix)

Soon I will post release 1.6.3 and everything will work
