### ISSUE TITLE
a function for non-coco format data

### ISSUE THREAD

**Issue by idejie** [MiXaiLL76/faster_coco_eval#4]
Is there a function for non-coco format? like:

```
box_gt = [[(x,y,w,h),(x,y,w,h),....],.....]
box_pred =  [[(x,y,w,h),(x,y,w,h),....],.....]
```

**Comment by MiXaiLL76** [comment]
no, only coco format is currently supported. But you can format your bboxes properly.
Or write a loader and make a PR
