### ISSUE TITLE
How to display mAP, P, R indicators by category?

### ISSUE THREAD

**Issue by Fridayfairy** [MiXaiLL76/faster_coco_eval#49]
Currently printed is, may I ask if there is an integrated category indicator printing interface?
DONE (t=3.04s). IoU metric: bbox Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.400 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.689 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.400 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.118 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.225 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.457 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.384 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.574 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.621 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.231 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.469 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.672 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.947 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.668

**Comment by MiXaiLL76** [comment]
Hi! No, it is not implemented.
But you can take the code from here:
https://github.com/open-mmlab/mmdetection/blob/main/mmdet/evaluation/metrics/coco_metric.py#L520
For work
